/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ComponentOne {
    }
    interface ComponentThree {
    }
    interface ComponentTwo {
    }
    interface KdsPriceStory {
        "alignment": string;
        "bottomRightMessage"?: string;
        "couponCode"?: string;
        "infoMessage"?: string;
        "orientation": string;
        "percentageOff"?: number;
        "priceData"?: string;
        "regularPrice"?: number;
        "regularPriceLabel"?: string;
        "salePrice"?: number;
        "salePriceLabel"?: string;
        "size": string;
        "yourPrice"?: number;
        "yourPriceLabel"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
export interface KdsPriceStoryCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLKdsPriceStoryElement;
}
declare global {
    interface HTMLComponentOneElement extends Components.ComponentOne, HTMLStencilElement {
    }
    var HTMLComponentOneElement: {
        prototype: HTMLComponentOneElement;
        new (): HTMLComponentOneElement;
    };
    interface HTMLComponentThreeElement extends Components.ComponentThree, HTMLStencilElement {
    }
    var HTMLComponentThreeElement: {
        prototype: HTMLComponentThreeElement;
        new (): HTMLComponentThreeElement;
    };
    interface HTMLComponentTwoElement extends Components.ComponentTwo, HTMLStencilElement {
    }
    var HTMLComponentTwoElement: {
        prototype: HTMLComponentTwoElement;
        new (): HTMLComponentTwoElement;
    };
    interface HTMLKdsPriceStoryElement extends Components.KdsPriceStory, HTMLStencilElement {
    }
    var HTMLKdsPriceStoryElement: {
        prototype: HTMLKdsPriceStoryElement;
        new (): HTMLKdsPriceStoryElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "component-one": HTMLComponentOneElement;
        "component-three": HTMLComponentThreeElement;
        "component-two": HTMLComponentTwoElement;
        "kds-price-story": HTMLKdsPriceStoryElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface ComponentOne {
    }
    interface ComponentThree {
    }
    interface ComponentTwo {
    }
    interface KdsPriceStory {
        "alignment"?: string;
        "bottomRightMessage"?: string;
        "couponCode"?: string;
        "infoMessage"?: string;
        "onInfoIconEvent"?: (event: KdsPriceStoryCustomEvent<any>) => void;
        "orientation"?: string;
        "percentageOff"?: number;
        "priceData"?: string;
        "regularPrice"?: number;
        "regularPriceLabel"?: string;
        "salePrice"?: number;
        "salePriceLabel"?: string;
        "size"?: string;
        "yourPrice"?: number;
        "yourPriceLabel"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "component-one": ComponentOne;
        "component-three": ComponentThree;
        "component-two": ComponentTwo;
        "kds-price-story": KdsPriceStory;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "component-one": LocalJSX.ComponentOne & JSXBase.HTMLAttributes<HTMLComponentOneElement>;
            "component-three": LocalJSX.ComponentThree & JSXBase.HTMLAttributes<HTMLComponentThreeElement>;
            "component-two": LocalJSX.ComponentTwo & JSXBase.HTMLAttributes<HTMLComponentTwoElement>;
            "kds-price-story": LocalJSX.KdsPriceStory & JSXBase.HTMLAttributes<HTMLKdsPriceStoryElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
